### ISSUE TITLE
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_users_on_uid" DETAIL: Key (uid)=(kbc) already exists.

### ISSUE THREAD

**Issue by christinach** [pulibrary/lockers_and_study_spaces#101]
https://app.honeybadger.io/projects/102902/faults/88201446

ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_uid" DETAIL:  Key (uid)=(kbc) already exists.

```
app/models/user.rb:18:in `from_cas'
def self.from_cas(access_token)
  user = User.find_by(provider: access_token.provider, uid: access_token.uid)
  user = User.create(provider: access_token.provider, uid: access_token.uid, admin: false) if 
  user.blank?
  user
end
```

**Comment by sandbergja** [comment]
One of the patrons affected by this issue submitted a libanswers ticket as well, saying that it blocked them from requesting a locker.
