### ISSUE TITLE
Add Lewis Library policy

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#110]
### User story

As a student, I would like to see Lewis Library's locker policy, rather than Firestone's, on the bottom of the application form.

### Concrete example

At https://lockers-and-study-spaces.princeton.edu, after you sign in, you can see Firestone's policy at the bottom of the form:

```
Lockers are assigned based on your eligibility by department,
application date, and applicant’s status. First priority will be
given to seniors and graduate students in their final year of
study. You will be notified by email when your locker is assigned.
After you receive notification, it is very important that you visit
the Access Office to complete the process. 
```

### Desired policy

We need to confirm the exact wording with stakeholders, but here are some hints:

- There is some policy language at the top of the existing form: https://library.princeton.edu/lewis/services/locker-request
- Here is a list of departments that are prioritized for a Lewis Locker: https://docs.google.com/document/d/18vvkFnEEyoFg_D5ZsE3wrzmHgln23_oFyYtpM35dJyQ/edit
- Preference is given to grad students

**Comment by kevinreiss** [comment]
Policy will articulated on the Drupal page linking to the application form.
