### ISSUE TITLE
Lists of locker applications should be scoped to the administrator's library

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#112]
### User story
As a lockers administrator, I would like to only see locker applications at my library.
As a lockers administrator, I would like confirm that I am managing the correct library in the header. 

### Concrete example

The l[ist of locker applications is already quite overwhelming](https://lockers-and-study-spaces.princeton.edu/locker_applications/). 

Acceptance criteria:

- [x] Include Library Name in the header
- [x] See locker applications only for your Library
- [x] See only locker applications awaiting assignment for your Library
- [x]  https://lockers-and-study-spaces-staging.princeton.edu/ 
- [x] https://lockers-and-study-spaces-staging.princeton.edu/locker_applications/
- [x] https://lockers-and-study-spaces-staging.princeton.edu/locker_applications/awaiting_assignment

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Work-Cycle-Board-571691cab409d8d821b873be/issues/pulibrary/lockers_and_study_spaces/112?planning-poker) with Zenhub @sandbergja @maxkadel @rladdusaw @christinach

**Comment by maxkadel** [comment]
Having issues with with authentication & nav bar.

**Comment by maxkadel** [comment]
This feature does not need to be behind the feature flipper.
