### ISSUE TITLE
Custom locker assignment email for Lewis lockers

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#115]
### User story

As a student, when I am assigned a locker, I would like to receive an email from the Lewis Library's email address with all the Lewis-specific information I need.

### Concrete examples

- Lewis lockers use keys, rather than combinations, so the email should not include a locker combination.
- Lewis locker emails should come from lewislib@princeton.edu, rather than access@princeton.edu

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Work-Cycle-Board-571691cab409d8d821b873be/issues/pulibrary/lockers_and_study_spaces/115?planning-poker) with Zenhub @christinach @maxkadel @rladdusaw @sandbergja
