### ISSUE TITLE
Add new lewis lockers in bulk 

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#116]
### User story

As a lockers administrator at Lewis, I would like the lockers to be loaded in this system before implementing it, so that I don't have to manually create each locker by hand. This is a one time task to see the system done by a developer possibly as a seed file and likely done with a rack task. 

### Implementation notes, if any

There are 104 lockers at Lewis (52 on each floor).  They are on the 3rd and 4th floors, and have the floor number as the first digit in their number. First lockers are 301 and 401. 

- Start with populating only locker number (in "location" field) and floor
- May need to update database validation to allow for lockers with less information

**Comment by kevinreiss** [comment]
Two questions for Lewis stakeholders to resolve:

1. Should lockers be labeled "301" or "3-01" or in some other way?
2. Which of the possible values in the current locker form are relevant for Lewis? 

![Image](https://user-images.githubusercontent.com/278825/197572310-e62e97e0-2463-4af3-b314-5440d9aab571.png)

**Comment by maxkadel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Work-Cycle-Board-571691cab409d8d821b873be/issues/pulibrary/lockers_and_study_spaces/116?planning-poker) with Zenhub @christinach @regineheberlein @sandbergja
