### ISSUE TITLE
Upgrade to Ruby 3.1.x

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lockers_and_study_spaces#118]
- [ ]  Add current Ruby 3.1.x to CircleCI
- [ ]  Fix any failing tests or dependency issues caused by upgrade to 3.1.x
- [ ]  Provision staging box to use Ruby 3.1.x
- [ ]  Deploy code that works with 3.1.x to staging
- [ ] Test on staging box with 3.1.x
- [ ] Provision production box to use Ruby 3.1.x
- [ ] Deploy to prod, confirm working on Ruby 3.1.x

**Comment by sandbergja** [comment]
closed by #166
