### ISSUE TITLE
Create wireframes for Locker Library Choice 

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#121]
Two ideas for the UI for students to select the library they'd like a locker at:

- Landing page that offers them two choices (Lewis or Firestone)
- No landing page, just a field on the locker application form.  Depending on the library they select, the options in the dropdown on the application form will change (see https://github.com/pulibrary/lockers_and_study_spaces/issues/109)

Acceptance criteria:

- Create a wireframe of each option
- Show them to stakeholders and see which one better meets the needs

**Comment by sandbergja** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Rails-62754f60cf98a10014f28e1e/issues/pulibrary/lockers_and_study_spaces/121?planning-poker) with Zenhub @maxkadel @rladdusaw @leefaisonr @christinach @regineheberlein

**Comment by christinach** [comment]
1. Prototype to review the dropdown Library menu in the lockers page. Selecting Lewis Library will update the 'Preferred General Area'. Library selection in this case is a submit.
https://xd.adobe.com/view/5818248e-39ab-45af-a711-b044dca095af-0d4b/ start from 1, then 2, then 3. or watch the mov file below.

https://user-images.githubusercontent.com/9905193/196440373-f27978d7-8203-4442-a996-a883e36bb049.mov

**Comment by christinach** [comment]
2. Select the Library and login.
The order to view the wireframes is 2,3,4,1
https://xd.adobe.com/view/4a29213b-99bf-4c8c-9a89-9e165a746bb7-1f7a/

**Comment by christinach** [comment]
mov file for option 2:

https://user-images.githubusercontent.com/9905193/196466400-de7f663e-7d0c-4f08-a740-379c22eb7320.mov

**Comment by christinach** [comment]
Option 2: Select the Library before login. The order to view the wireframes is 1,2,3,4,5.
wireframes/prototypes: https://xd.adobe.com/view/4a29213b-99bf-4c8c-9a89-9e165a746bb7-1f7a/

Movie file:

https://user-images.githubusercontent.com/9905193/196489619-191ca9aa-ca90-4a2f-b075-27b00106067f.mov

**Comment by christinach** [comment]
Option 2. Select the library before login
Wireframes: https://xd.adobe.com/view/4a29213b-99bf-4c8c-9a89-9e165a746bb7-1f7a/

Movie file:

https://user-images.githubusercontent.com/9905193/196532043-a78a57a6-baf3-4e9e-9414-0ef3e9ad3b01.mov

**Comment by christinach** [comment]
Emailed the wireframes and demo to the stakeholders on 10/18/22. We are having a meeting today 10/21/22.

**Comment by christinach** [comment]
From stakeholders meeting: We want the user to Login first with CAS and then in a different landing page select the Library to proceed. Then redirect them to the locker application page.

**Comment by christinach** [comment]
New wireframe following the discussion with the stakeholders. https://xd.adobe.com/view/4a29213b-99bf-4c8c-9a89-9e165a746bb7-1f7a/

**Comment by christinach** [comment]
This was completed.
