### ISSUE TITLE
Allow users to request specific accessibility needs

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/lockers_and_study_spaces#125]
### User story
As a student with both visual impairment and mobility accessibility needs, I'd like to communicate my specific accessibility needs when requesting a locker.

### Concrete example
It takes different accommodations in order to make a locker accessible to someone. 

We can offer a checklist of known accommodations, including being near and elevator, keyed entry rather than combination, as well as adding a write-in space for accommodations we may be able to provide for but may not be able to anticipate ahead of time, such as a locker in a quieter space for people with sensory sensitivities. 

### Implementation notes, if any
This could be a multi-select list with an additional "other" write-in field.

**Comment by kevinreiss** [comment]
Double check with Lewis staff if they have options that are related to accessibility that they'd like enumerated or if they would like just a free-text field.

**Comment by maxkadel** [comment]
Proposal in order to not be blocked by Lux work:

- 2 check boxes - one for each accessibility need, then one text box for additional needs

Create mockup and send to stakeholders to get buyin.
