### ISSUE TITLE
Seed data will need to be made aware of the new Building model

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#136]
### User story
As a developer, when I run `db:seed`, and all the admin users and lockers are created with the correct `building_id` values in the database.

### Current status

The `space_admins.csv` and `spaces.csv` files don't even have a column for the building yet.

Possibly related to #116, in that this ticket is also about seeding lockers.

**Comment by maxkadel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Work-Cycle-Board-571691cab409d8d821b873be/issues/pulibrary/lockers_and_study_spaces/136?planning-poker) with Zenhub @kevinreiss @sandbergja @christinach @rladdusaw @regineheberlein

**Comment by maxkadel** [comment]
The seeds are built from CSV files that are on the servers, but it is not clear to me how the original files were generated or the best way to re-generate them.

**Comment by maxkadel** [comment]
* Right now the seeds & CSVs are still from the original database
* The seeds are not idempotent

* What do we want from the seeds at this point? Should they just populate a development environment? Do we want to be able to use them to create a whole environment? If so, would a full database dump & upload be more effective?
