### ISSUE TITLE
Indicate required fields on the client side in new locker form.

### ISSUE THREAD

**Issue by christinach** [pulibrary/lockers_and_study_spaces#138]
### Current display
The new locker screen does not indicate which fields are required in order for the application submission to be  successful.  

### Desired display
The new locker screen should indicate which fields are required in order for the application submission to be  successful. 

Include `required=true` in the html input for the specific field.

![Screen Shot 2022-10-26 at 2 25 32 PM](https://user-images.githubusercontent.com/9905193/198106634-940c4509-fa20-4758-84b1-cee8af735f0b.png)

**Comment by sandbergja** [comment]
required fields are in the model: https://github.com/pulibrary/lockers_and_study_spaces/blob/f4b118f4230854e5831113698e868e39fef32eb8/app/models/locker.rb#L4-L6

**Comment by maxkadel** [comment]
Closed by #153
