### ISSUE TITLE
As an admin I'm assigned to a library and don't need to select a library after logging in

### ISSUE THREAD

**Issue by christinach** [pulibrary/lockers_and_study_spaces#145]
### Current display
Admin users see the library dropdown.

### Desired display
Admin users don't need to see the library dropdown.

**Comment by maxkadel** [comment]
Any new Locker Applications that admins create should be in their "home" library, they should not need to select a library. 

When the Lewis Patron feature is on:
  * Students will have a two step Locker Application Process, where they need to do the second step to mark application complete
  * Admins will have a one step Locker Application Process, where any application they create will be marked as complete
