### ISSUE TITLE
As an admin user I should be able to edit the netid when I create a new locker application.

### ISSUE THREAD

**Issue by christinach** [pulibrary/lockers_and_study_spaces#146]
### Expected behavior
As an admin user I should be able to edit the locker application with a different netid.

### Actual behavior
As an admin user when I edit the locker application with a different netid it does not persist. Every time I click another field or outside of the netid field it will change the value back to my netid. 

### Steps to replicate

https://user-images.githubusercontent.com/9905193/199262634-884d682c-0e7c-4375-aa34-4fed4eded8f5.mov

### Impact of this bug
Every application I submit as an admin has my netid. 

```
```

**Comment by maxkadel** [comment]
Currently, this works if the user has already logged in to the Lockers and Study Spaces application, thus creating a User, but does not work if the user has never logged in.
