### ISSUE TITLE
When I create a locker application it does not submit it. 

### ISSUE THREAD

**Issue by christinach** [pulibrary/lockers_and_study_spaces#150]
### Expected behavior
When I create a new locker application I should be able to view it in the Locker Applications list.

### Actual behavior
When I create a locker application it does not submit it and I cannot view it in the Locker Applications list. I have to click on Edit and submit (update) in order to view it in the 'Applications list'.

### Steps to replicate
https://lockers-and-study-spaces-staging.princeton.edu/ fill out the fields and 'Submit Locker application' ; Locker management -> All applications . The application is not there. 

### Notes
When I create a new locker application it does not complete it. (complete remains false)

**Comment by maxkadel** [comment]
I think this *may* be fixed by https://github.com/pulibrary/lockers_and_study_spaces/pull/147

**Comment by maxkadel** [comment]
I think this is actually a feature - the idea is that half-made applications don't clutter up the administrator's list. We may want to change it, but it was requested.

**Comment by sandbergja** [comment]
See duplicate bug #157 for more details.

While addressing this, we should make sure not to add any regressions on https://github.com/pulibrary/lockers_and_study_spaces/pull/142 -- particularly when the Lewis Patrons feature flipper is on.

**Comment by maxkadel** [comment]
When the Lewis feature is off: 
  * Any new Locker applications should show in the Locker Applications List (should be marked "complete")

When the Lewis feature is on:
  * Incomplete Locker applications should not show in the Locker Applications List (those with only UID & Library)
  * Locker applications that are more complete (implementation?) should be marked as complete and show on the Locker Applications List
