### ISSUE TITLE
Learn more about Lewis' need for renewal notifications

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#200]
### Background

Firestone admins have access to a feature that lets them schedule renewal emails.  After we complete #199, Lewis admins will no longer have access to such a feature.  We're not sure if they would need such a feature.  If they do, they might need to supply new, Lewis-specific text.

### Acceptance criteria

- [x] I have asked Lewis stakeholders what their needs are for renewal notifications
- [x] If they need some kind of notification, I have ticketed it

**Comment by kevinreiss** [comment]
Wrote lewis staff 2/24.

**Comment by kevinreiss** [comment]
Lewis would like to have the same renewal workflow for their lockers that Firestone uses.

**Comment by kevinreiss** [comment]
Created issue to implement feature at https://github.com/pulibrary/lockers_and_study_spaces/issues/201
