### ISSUE TITLE
missing .sprockets-manifest and .manifest

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/lockers_and_study_spaces#242]
### Expected behavior

when attempting to deploy on a brand new VM I expect the deploy to complete successfully. 

### Actual behavior
the deploy fails with the following
![Screenshot 2023-09-08 at 4 05 57 PM](https://github.com/pulibrary/lockers_and_study_spaces/assets/685884/b776bd7d-fae5-4619-8492-ebffbcb3361a)

### Steps to replicate

```bash
ssh deploy@lockers-and-study-spaces-staging2
rm /opt/lockers_and_study_spaces/shared/public/assets/.manifest.json
rm /opt/lockers_and_study_spaces/shared/public/assets/.sprockets-manifest.json
```
then try to run

```bash
bundle exec cap staging deploy
```

### Impact of this bug

If you replace the files above with:

```bash
touch /opt/lockers_and_study_spaces/shared/public/assets/.manifest.json
touch /opt/lockers_and_study_spaces/shared/public/assets/.sprockets-manifest.json
```

### Honeybadger link and code snippet, if applicable

```
```

**Comment by maxkadel** [comment]
I looked at staging1, and it looks like the most recent files on there are from January 25, 2023. I'm wondering if something broke in the assets pipeline around that time, and we just didn't realize because it was using the pre-existing assets?

**Comment by maxkadel** [comment]
The only deploy on January 25, 2023, was 
```
Branch main (at d9851db5a2b4d33e3afb4c88e9dc972033b33f21) deployed as release 20230125162403 by deploy
```

The next deploy, which did not create a new sprockets-manifest file, was
```
Branch main (at bb4edf501c9aa421a2150e45075ddb394cb0a421) deployed as release 20230210175920 by colec
```

**Comment by sandbergja** [comment]
...like me trying to remove sprockets on that date, for example? https://github.com/pulibrary/lockers_and_study_spaces/pull/173
