### ISSUE TITLE
Firestone Edit Requests

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lockers_and_study_spaces#246]
April asked if the following three edits are possible. 

- [x]  In the list for Firestone Locker general areas when on the search assignment page, A-5-7 is listed but there aren't any lockers in that area. Can you please remove A-5-7 from the drop down list? 
- [x]  There is also a locker called defunct which can be removed.

**Comment by sandbergja** [comment]
Completed this by removing the relevant rows from the database, after confirming with April that no statistics were needed for these lockers.
