### ISSUE TITLE
Update Banner to be non Firestone Specific

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lockers_and_study_spaces#247]
From April:

Since the database is shared with Lewis Library, can the banner be changed so it doesn't say Firestone Library? 

We will update the banner to say: 'Princeton University Library lockers and study rooms'

**Comment by maxkadel** [comment]
Probable relevant code - [app/views/layouts/application.html.erb#L15](https://github.com/pulibrary/lockers_and_study_spaces/blob/0d87639d96cabdca0ef3b700a24700b24cddfd73/app/views/layouts/application.html.erb#L15 )
