### ISSUE TITLE
Upgrade to rails 7.1 or 7.2

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#265]
### What maintenance needs to be done?

Upgrade to rails 7.1 or (if it has been released yet) 7.2

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- So that we don't get too far behind on rails versions

### Acceptance criteria
 - [ ]  We use version 7.1 or 7.2 of rails

**Comment by kevinreiss** [comment]
Looks like we moved to 7.1 last week: https://github.com/pulibrary/lockers_and_study_spaces/commit/cac83d2f6f2505decbd7e16eb85d090a1cc1d26d.
