### ISSUE TITLE
Add a New Admin User for Lewis 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lockers_and_study_spaces#287]
### What maintenance needs to be done?
Kelee from Lewis requests that Alex Amaniampong be added as an admin for the Lewis Library Lockers. 

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
Alex will be the primary manager of this service from Lewis. 

### Acceptance criteria
 - [x] Alex Amaniampong is an admin for lewis lockers
 - [x] A brief orientation call is conducted with Alex on how to use the system. 
  
### Implementation notes, if any
Alex is available any day next week (Starting on 5/28) to speak.

**Comment by rladdusaw** [comment]
Alex was added as an admin to staging and prod and given an overview of the app over zoom.
