### ISSUE TITLE
Upgrade lux to version 5

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#298]
### What maintenance needs to be done?

Upgrade lux-design-system npm dependency to version 5.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- We can get new updates to lux
- We can move away from Vue 2, which is past its EOL

### Acceptance criteria
 - [x] We use version 5.0.0 or higher of lux-design-system

### Implementation notes, if any

[Upgrade instructions](https://github.com/pulibrary/lux-design-system/blob/main/UpgradeInstructions.md)

**Comment by christinach** [comment]
resolved by https://github.com/pulibrary/lockers_and_study_spaces/pull/315
